version: "3.5"

services:
  ant-design-pro_dev:
    ports:
      - 8005:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "skylla_test"
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
    networks:
      default:
        external:
          name: skylla_default
